In [32]:
from deck import full_euchre_deck
from dealer import Dealer
from sim_game import game_sim
from sim_game_list_comp import lc_game_sim
from branch_calc import calc_all_possible_hands, filter_branch_by_hand
import numpy as np

In [33]:
game = Dealer(deck=full_euchre_deck ,players=4)
game.deal_cards()
hands5 = [game.hand1, game.hand2, game.hand3, game.hand4]
v_hands = 5*[hands5]
hands5
# first_play = [game.hand1[0], game.hand1[1], game.hand1[2], game.hand1[3], game.hand1[4]]

[array([[ 12,   0],
        [ 11,   0],
        [  0, 120],
        [  0, -13],
        [  0, -10]]),
 array([[-13,   0],
        [ 14,   0],
        [ 10,   0],
        [-10,   0],
        [  0,  -9]]),
 array([[  0, -14],
        [  0, 140],
        [  0, 100],
        [  0, 135],
        [ 13,   0]]),
 array([[  0, 130],
        [  0,  90],
        [-14,   0],
        [-11,   0],
        [ -9,   0]])]

In [34]:
# put this here for verification and debugging purposes
test = calc_all_possible_hands(hands5)

In [35]:
# put this here for verification and debugging purposes
for i in range(5):
    target = game.hand1[i]

    contains_target = np.any(
        np.all(test == target, axis=-1), axis=1
    )
    contains_target
    stump = test[contains_target]
    stump = filter_branch_by_hand(stump, game.hand2, 1, target)
    stump = filter_branch_by_hand(stump, game.hand3, 2, target)
    stump = filter_branch_by_hand(stump, game.hand4, 3, target)
    print(len(stump))

6
6
6
3
3


In [41]:
game_sim(dealt_hands=hands5)

24
711
6032
18690


0.052969502407704656