In [1]:
from dataclasses import dataclass
import numpy as np
from deck import full_euchre_deck
from branch_calc import (
    filter_branch_by_hand,
    setdiff2d_idx,
    suit_id,
    find_winner,
    calc_all_possible_hands,
)
from dealer import Dealer

In [2]:
game = Dealer(deck=full_euchre_deck ,players=4)
game.deal_cards()
hands5 = [game.hand1, game.hand2, game.hand3, game.hand4]
# first_play = [game.hand1[0], game.hand1[1], game.hand1[2], game.hand1[3], game.hand1[4]]

In [3]:
@dataclass
class PlayRound:
    hands: list
    winner: int

    def play_round(self, bit: int):
        all_possible_tricks = calc_all_possible_hands(hands=self.hands)
        len(all_possible_tricks)
        contains_target = np.any(
            np.all(all_possible_tricks == self.hands[self.winner][bit], axis=-1), axis=1
        )
        stump = all_possible_tricks[contains_target]
        stump = filter_branch_by_hand(stump, self.hands[(self.winner+1)%4], (self.winner+1)%4, self.hands[self.winner][bit])
        stump = filter_branch_by_hand(stump, self.hands[(self.winner+2)%4], (self.winner+2)%4, self.hands[self.winner][bit])
        stump = filter_branch_by_hand(stump, self.hands[(self.winner+3)%4], (self.winner+3)%4, self.hands[self.winner][bit])
        self.round_winner = find_winner(
            lead=stump[bit][self.winner], trick=stump[bit]
        )  # will need to fix this in order to iterate through all hands
        self.round_winning_team = (
            find_winner(lead=stump[bit][self.winner], trick=stump[bit]) % 2
        )  # will need to fix this in order to iterate through all hands
        self.next_round_hands = [
            setdiff2d_idx(self.hands[0], stump[bit]),
            setdiff2d_idx(self.hands[1], stump[bit]),
            setdiff2d_idx(self.hands[2], stump[bit]),
            setdiff2d_idx(self.hands[3], stump[bit]),
        ]

        return (
            stump[bit],
            self.round_winner,
            self.round_winning_team,
            np.array(self.next_round_hands),
        )


In [4]:
round1 = PlayRound(hands=hands5, winner=0)
round1.play_round(bit=0)

(array([[  0, -12],
        [  0, 140],
        [  0, -11],
        [  0, -13]]),
 1,
 1,
 array([[[ -11,    0],
         [ -13,    0],
         [ -12,    0],
         [   9,    0]],
 
        [[   0,  130],
         [   0, -135],
         [  -9,    0],
         [ -14,    0]],
 
        [[  13,    0],
         [  11,    0],
         [ -10,    0],
         [  10,    0]],
 
        [[   0,  100],
         [   0,   -9],
         [   0,  110],
         [  14,    0]]]))

In [5]:
round2 = PlayRound(hands=round1.next_round_hands, winner=round1.round_winner)
round2.play_round(bit=0)

(array([[-11,   0],
        [  0, 130],
        [ 13,   0],
        [  0, 100]]),
 1,
 1,
 array([[[ -13,    0],
         [ -12,    0],
         [   9,    0]],
 
        [[   0, -135],
         [  -9,    0],
         [ -14,    0]],
 
        [[  11,    0],
         [ -10,    0],
         [  10,    0]],
 
        [[   0,   -9],
         [   0,  110],
         [  14,    0]]]))

In [6]:
stop

NameError: name 'stop' is not defined

In [ ]:
all_possible_tricks = calc_all_possible_hands(hands=round1.next_round_hands)
contains_target = np.any(
    np.all(all_possible_tricks == hands[2][0], axis=-1), axis=1
)
stump = all_possible_tricks[contains_target]
stump = filter_branch_by_hand(stump, hands[(2+1)%4], 1, first_play[0])
stump = filter_branch_by_hand(stump, hands[(2+2)%4], 2, first_play[0])
stump = filter_branch_by_hand(stump, hands[(2+3)%4], 3, first_play[0])
stump
# round_winner = find_winner(
#     lead=stump[0][2], trick=stump[0]
#         )  # will need to fix this in order to iterate through all hands

array([], shape=(0, 4, 2), dtype=int32)

In [ ]:
round2 = PlayRound(hands=round1.next_round_hands, winner=round1.round_winner)
round2.play_round(bit=0)

(array([[  0, 140],
        [-12,   0],
        [  0, 100],
        [-11,   0]]),
 0,
 0,
 array([[[   0,  130],
         [  13,    0],
         [   0, -135],
         [ -13,    0]],
 
        [[   0,  -13],
         [   0,  -12],
         [  -9,    0],
         [  11,    0]],
 
        [[ -14,    0],
         [   0,   -9],
         [   0,   90],
         [   0,  110]],
 
        [[ -10,    0],
         [  10,    0],
         [  14,    0],
         [   0,  -10]]]))

In [ ]:
all_possible_tricks = calc_all_possible_hands(hands=hands)
len(all_possible_tricks)
contains_target = np.any(np.all(all_possible_tricks == first_play[0], axis=-1), axis=1)
stump = all_possible_tricks[contains_target]
stump = filter_branch_by_hand(stump , game.hand2, 1, first_play[0])
stump = filter_branch_by_hand(stump, game.hand3, 2, first_play[0])
stump = filter_branch_by_hand(stump, game.hand4, 3, first_play[0])
 


In [ ]:
winner = find_winner(lead=stump[0][0], trick=stump[0]) 
winning_team = find_winner(lead=stump[0][0], trick=stump[0]) % 2

In [ ]:
len(stump), stump[0]

(75,
 array([[  0, 130],
        [  0, -13],
        [  0,  90],
        [-10,   0]]))

In [ ]:

winner, winning_team

(0, 0)

In [ ]:
# this is maybe how we can solve for recursion
game.hand1 = setdiff2d_idx(game.hand1, stump[0])

In [ ]:
game.hand1

array([[   0,  140],
       [  13,    0],
       [   0, -135],
       [ -13,    0]])

In [ ]:
rd2_hands = [setdiff2d_idx(game.hand1, stump[0]),
setdiff2d_idx(game.hand2, stump[0]),
setdiff2d_idx(game.hand3, stump[0]),
setdiff2d_idx(game.hand4, stump[0])]
all_possible_tricks = calc_all_possible_hands(hands=rd2_hands)
len(all_possible_tricks), rd2_hands

(256,
 [array([[   0,  140],
         [  13,    0],
         [   0, -135],
         [ -13,    0]]),
  array([[-12,   0],
         [  0, -12],
         [ -9,   0],
         [ 11,   0]]),
  array([[-14,   0],
         [  0,  -9],
         [  0, 100],
         [  0, 110]]),
  array([[-11,   0],
         [ 10,   0],
         [ 14,   0],
         [  0, -10]])])

In [ ]:
rd2_contains_target = np.any(np.all(all_possible_tricks == rd2_hands[winner][0], axis=-1), axis=1)
rd2_stump = all_possible_tricks[rd2_contains_target]

rd2_stump = filter_branch_by_hand(rd2_stump , rd2_hands[(winner+1)%4], (winner+1)%4, rd2_hands[winner][0])
rd2_stump = filter_branch_by_hand(rd2_stump, rd2_hands[(winner+2)%4], (winner+2)%4, rd2_hands[winner][0])
rd2_stump = filter_branch_by_hand(rd2_stump, rd2_hands[(winner+3)%4], (winner+3)%4, rd2_hands[winner][0])
len(rd2_stump)

32

In [ ]:
rd2_stump

array([[[  0, 140],
        [-12,   0],
        [  0, 100],
        [-11,   0]],

       [[  0, 140],
        [-12,   0],
        [  0, 100],
        [ 10,   0]],

       [[  0, 140],
        [-12,   0],
        [  0, 100],
        [ 14,   0]],

       [[  0, 140],
        [-12,   0],
        [  0, 100],
        [  0, -10]],

       [[  0, 140],
        [-12,   0],
        [  0, 110],
        [-11,   0]],

       [[  0, 140],
        [-12,   0],
        [  0, 110],
        [ 10,   0]],

       [[  0, 140],
        [-12,   0],
        [  0, 110],
        [ 14,   0]],

       [[  0, 140],
        [-12,   0],
        [  0, 110],
        [  0, -10]],

       [[  0, 140],
        [  0, -12],
        [  0, 100],
        [-11,   0]],

       [[  0, 140],
        [  0, -12],
        [  0, 100],
        [ 10,   0]],

       [[  0, 140],
        [  0, -12],
        [  0, 100],
        [ 14,   0]],

       [[  0, 140],
        [  0, -12],
        [  0, 100],
        [  0, -10]],

       [[  0, 14

In [ ]:
winner = find_winner(lead=rd2_hands[winner][0], trick=rd2_stump[0]) 
winning_team = find_winner(lead=rd2_hands[winner][0], trick=rd2_stump[0]) % 2
winner, winning_team, rd2_stump[0]

(0,
 0,
 array([[  0, 140],
        [-12,   0],
        [  0, 100],
        [-11,   0]]))

In [ ]:
rd3_hands = [setdiff2d_idx(rd2_hands[0], rd2_stump[0]),
setdiff2d_idx(rd2_hands[1], rd2_stump[0]),
setdiff2d_idx(rd2_hands[2], rd2_stump[0]),
setdiff2d_idx(rd2_hands[3], rd2_stump[0])]
all_possible_tricks = calc_all_possible_hands(hands=rd3_hands)
len(all_possible_tricks)

81

In [ ]:
rd3_hands

[array([[  13,    0],
        [   0, -135],
        [ -13,    0]]),
 array([[  0, -12],
        [ -9,   0],
        [ 11,   0]]),
 array([[-14,   0],
        [  0,  -9],
        [  0, 110]]),
 array([[ 10,   0],
        [ 14,   0],
        [  0, -10]])]

In [ ]:
rd3_hands[winner][0]

array([13,  0])

In [ ]:
rd3_contains_target = np.any(np.all(all_possible_tricks == rd3_hands[winner][0], axis=-1), axis=1)
rd3_stump = all_possible_tricks[rd3_contains_target]

rd3_stump = filter_branch_by_hand(rd3_stump , rd3_hands[(winner+1)%4], (winner+1)%4, rd3_stump[winner][0])
rd3_stump = filter_branch_by_hand(rd3_stump, rd3_hands[(winner+2)%4], (winner+2)%4, rd3_stump[winner][0])
rd3_stump = filter_branch_by_hand(rd3_stump, rd3_hands[(winner+3)%4], (winner+3)%4, rd3_stump[winner][0])
len(rd3_stump)

6

In [ ]:
winner = find_winner(lead=rd3_hands[winner][0], trick=rd3_stump[0]) 
winning_team = find_winner(lead=rd3_hands[winner][0], trick=rd3_stump[0])  % 2
winner, winning_team, rd3_stump[0]

(0,
 0,
 array([[ 13,   0],
        [ 11,   0],
        [-14,   0],
        [ 10,   0]]))

In [ ]:
rd4_hands = [setdiff2d_idx(rd3_hands[0], rd3_stump[0]),
setdiff2d_idx(rd3_hands[1], rd3_stump[0]),
setdiff2d_idx(rd3_hands[2], rd3_stump[0]),
setdiff2d_idx(rd3_hands[3], rd3_stump[0])]
all_possible_tricks = calc_all_possible_hands(hands=rd4_hands)
len(all_possible_tricks)

16

In [ ]:
rd4_hands

[array([[   0, -135],
        [ -13,    0]]),
 array([[  0, -12],
        [ -9,   0]]),
 array([[  0,  -9],
        [  0, 110]]),
 array([[ 14,   0],
        [  0, -10]])]

In [ ]:
rd4_contains_target = np.any(np.all(all_possible_tricks == rd4_hands[winner][0], axis=-1), axis=1)
rd4_stump = all_possible_tricks[rd4_contains_target]

rd4_stump = filter_branch_by_hand(rd4_stump , rd4_hands[(winner+1)%4], (winner+1)%4, rd4_stump[winner][0])
rd4_stump = filter_branch_by_hand(rd4_stump, rd4_hands[(winner+2)%4], (winner+2)%4, rd4_stump[winner][0])
rd4_stump = filter_branch_by_hand(rd4_stump, rd4_hands[(winner+3)%4], (winner+3)%4, rd4_stump[winner][0])
len(rd4_stump)

4

In [ ]:
winner = find_winner(lead=rd4_hands[winner][0], trick=rd4_stump[0]) 
winning_team = find_winner(lead=rd4_hands[winner][0], trick=rd4_stump[0])  % 2
winner, winning_team, rd4_stump[0]

(0,
 0,
 array([[   0, -135],
        [   0,  -12],
        [   0,  110],
        [  14,    0]]))

In [ ]:
rd5_hands = [setdiff2d_idx(rd4_hands[0], rd4_stump[0]),
setdiff2d_idx(rd4_hands[1], rd4_stump[0]),
setdiff2d_idx(rd4_hands[2], rd4_stump[0]),
setdiff2d_idx(rd4_hands[3], rd4_stump[0])]
all_possible_tricks = calc_all_possible_hands(hands=rd5_hands)
len(all_possible_tricks)

1

In [ ]:
rd5_hands

[array([[-13,   0]]),
 array([[-9,  0]]),
 array([[ 0, -9]]),
 array([[  0, -10]])]

In [ ]:
winner = find_winner(lead=rd5_hands[winner], trick=rd5_hands) 
winning_team = find_winner(lead=rd5_hands[winner], trick=rd5_hands)  % 2
winner, winning_team, rd5_hands

IndexError: index 1 is out of bounds for axis 0 with size 1