In [21]:
from deck import full_euchre_deck
# from dealer import Dealer
from sim_game import game_sim
from branch_calc import compute_set_difference
import numpy as np

In [22]:
from dataclasses import dataclass

@dataclass
class Dealer:
    deck: np.ndarray
    players: int


    def __post_init__(self):
        self.hands = {}
        for i in range(1, 5):
            self.hands[f'hand{i}'] = []

    def stack_deck(self, stack_cards: np.array, player: int):
        self.hands[f'hand{player}'] = stack_cards
        remove = np.isin(self.deck, stack_cards).all(axis=1)
        self.deck = self.deck[~remove]
        return self.hands[f'hand{player}']
    
    def deal_cards(self) -> None:
        remaining_cards = np.arange(0, len(self.deck))

        
        # Deal 5 cards to players
        for i in self.hands:
            card_count = len(self.hands[i])
            if card_count == 0 :
                deal = np.random.choice(remaining_cards, size=5, replace=False)
                dealt_hand = self.deck[deal]
                self.hands[i] = dealt_hand 
                remaining_cards = np.setdiff1d(remaining_cards, deal)
            elif card_count == 5:
                setattr(self, i, self.hands[i])
                continue
            else:
                deal = np.random.choice(remaining_cards, size=5-card_count, replace=False)
                # print(self.hands[i])
                dealt_hand = np.vstack((self.hands[i], self.deck[deal]))
                self.hands[i] = dealt_hand
                remaining_cards = np.setdiff1d(remaining_cards, deal)
            
            #  set individual hand attributes
            setattr(self, i, dealt_hand)

In [29]:
stack_cards1 = np.array([[0, 135], [ 0, 140], [9, 0], [-9, 0], [0, -9]])

In [30]:
game = Dealer(deck=full_euchre_deck ,players=4)
game.stack_deck(stack_cards=stack_cards1, player=1)
game.deal_cards()
hands5 = [game.hand1, game.hand2, game.hand3, game.hand4]
hands5


# hands5 = [game.hand1, game.hand2, game.hand3, game.hand4]
# v_hands = 5*[hands5]
# first_play = [game.hand1[0], game.hand1[1], game.hand1[2], game.hand1[3], game.hand1[4]]

[array([[  0, 135],
        [  0, 140],
        [  9,   0],
        [ -9,   0],
        [  0,  -9]]),
 array([[  0, 100],
        [  0, -13],
        [  0, 110],
        [  0,  90],
        [ 11,   0]]),
 array([[ 14,   0],
        [-13,   0],
        [-14,   0],
        [ 10,   0],
        [ 12,   0]]),
 array([[  0, 130],
        [  0, -12],
        [ 13,   0],
        [-11,   0],
        [  0, -10]])]

In [31]:
game_sim(dealt_hands=hands5)

15
238
2603
9386


0.09460899211591732