In [26]:
from deck import full_euchre_deck
from play_round import PlayRound, find_winners_vectorized
from dealer import Dealer
from branch_calc import compute_set_difference
from sim_game import game_sim
import pandas as pd
import numpy as np

In [27]:
game = Dealer(deck=full_euchre_deck ,players=4)
game.deal_cards()
hands5 = [game.hand1, game.hand2, game.hand3, game.hand4]
v_hands = 5*[hands5]
hands5
# first_play = [game.hand1[0], game.hand1[1], game.hand1[2], game.hand1[3], game.hand1[4]]

[array([[  9,   0],
        [-11,   0],
        [  0, -13],
        [ 14,   0],
        [ 13,   0]]),
 array([[-13,   0],
        [ -9,   0],
        [-14,   0],
        [ 10,   0],
        [  0, 120]]),
 array([[-12,   0],
        [  0,  -9],
        [-10,   0],
        [  0,  90],
        [  0, -11]]),
 array([[  0, -10],
        [  0, 130],
        [  0, 140],
        [  0, -12],
        [  0, 110]])]

In [28]:
leads = [[i] for i in range(5)]

In [29]:
np.array(list(map(game_sim, v_hands, leads)))

25
664
23544
235328
30
1348
44910
456608
20
1968
57471
561256
25
1664
39156
366040
25
1664
39912
369848


array([1., 1., 1., 1., 1.])

In [30]:
game_sim(dealt_hands=hands5)

125
7308
204993
1989080


1.0