In [9]:
from deck import full_euchre_deck
from dealer import Dealer
from n_game_sim import n_game_sim
from n_play_round import round1, next_round
from tree_search import find_best_opener #, r2_best_response
import numpy as np
from numba import njit

In [198]:
game = Dealer(deck=full_euchre_deck ,players=4)
# game.stack_deck(stack_cards=dealer_pick, player=4)
game.deal_cards()
hands5 = np.array([game.hand1, game.hand2, game.hand3, game.hand4])
hands5

array([[[  0,  90],
        [  0, 120],
        [ 13,   0],
        [ 11,   0],
        [ 12,   0]],

       [[  0, -13],
        [-10,   0],
        [ 10,   0],
        [  0, 100],
        [  9,   0]],

       [[  0, 140],
        [  0, -10],
        [ -9,   0],
        [ 14,   0],
        [  0,  -9]],

       [[-12,   0],
        [-14,   0],
        [  0, 130],
        [  0, -14],
        [  0, 110]]])

In [199]:
r2_leads, r2_hands  = round1(hands_dealt=hands5, chosen_card=2)

In [200]:
r2_hands

array([[[[  0,  90],
         [  0, 120],
         [ 11,   0],
         [ 12,   0]],

        [[  0, -13],
         [-10,   0],
         [ 10,   0],
         [  0, 100]],

        [[  0, 140],
         [  0, -10],
         [ -9,   0],
         [  0,  -9]],

        [[-14,   0],
         [  0, 130],
         [  0, -14],
         [  0, 110]]],


       [[[  0,  90],
         [  0, 120],
         [ 11,   0],
         [ 12,   0]],

        [[  0, -13],
         [-10,   0],
         [ 10,   0],
         [  0, 100]],

        [[  0, 140],
         [  0, -10],
         [ -9,   0],
         [  0,  -9]],

        [[-12,   0],
         [-14,   0],
         [  0, -14],
         [  0, 110]]],


       [[[  0,  90],
         [  0, 120],
         [ 11,   0],
         [ 12,   0]],

        [[  0, -13],
         [-10,   0],
         [ 10,   0],
         [  0, 100]],

        [[  0, 140],
         [  0, -10],
         [ -9,   0],
         [  0,  -9]],

        [[-12,   0],
         [-14,   0],
        

In [201]:
best_opener = find_best_opener(hands=hands5)

[0.60824742 0.53367876 0.69230769 0.69230769 0.69230769]


In [202]:
# will likely need multiple perspectives here. 
r2_best_response(hands=hands5, best_opening_card=best_opener, player=1)

[0.         0.         0.         0.         0.03990025]


(array([ True, False, False]), array([ True, False, False]))

In [205]:
hands5

array([[[  0,  90],
        [  0, 120],
        [ 13,   0],
        [ 11,   0],
        [ 12,   0]],

       [[  0, -13],
        [-10,   0],
        [ 10,   0],
        [  0, 100],
        [  9,   0]],

       [[  0, 140],
        [  0, -10],
        [ -9,   0],
        [ 14,   0],
        [  0,  -9]],

       [[-12,   0],
        [-14,   0],
        [  0, 130],
        [  0, -14],
        [  0, 110]]])

In [203]:
# @njit
# def r2_best_response(hands, best_opening_card, player):
#     r2_leads, r2_hands = round1(hands_dealt=hands, chosen_card=best_opening_card)
#     resp_win_chances = np.zeros(5)
#     response_hands = np.zeros((5, len(r2_hands)), np.bool_)
#     response_leads = np.zeros((5, len(r2_hands)), np.bool_)
#     counter = 0
#     comp_hand = hands[player]

#     for i in comp_hand:
#         # initiate over arching mask
#         big_mask = np.zeros(len(r2_hands), dtype=np.bool_)
#         # give it a counter
#         big_counter = 0
#         for j in r2_hands:
#             # for each hand set in r2_hands, check if "i" is in it
#             mask = np.zeros(4, dtype=np.bool_)
#             m_counter = 0
#             for k in j[player]:
#                 # if this comes back as all false, it means card "i" was used
#                 # otherwise the card was not used, since its still there 
#                 mask[m_counter] = not np.all(i==k)
#                 m_counter += 1

#             big_mask[big_counter] = np.all(mask)

#         if np.sum(big_mask) == 0:
#             counter +=1 
#             continue
        
#         # arr_contiguous = np.ascontiguousarray(r2_hands[mask])
#         # arr_reshaped = arr_contiguous.reshape(1, 4, 4, 2)
#         r3_leads, r3_hands, r2_score = next_round(
#                 current_hands=r2_hands[big_mask],
#                 leads=r2_leads[big_mask],
#                 game_round=2,
#                 game_score=r2_leads[big_mask].reshape(-1, 1),
#             )
#         r4_leads, r4_hands, r3_score = next_round(
#             current_hands=r3_hands, leads=r3_leads, game_round=3, game_score=r2_score
#         )
#         r5_leads, r5_hands, r4_score = next_round(
#             current_hands=r4_hands, leads=r4_leads, game_round=4, game_score=r3_score
#         )
#         r6_leads, r6_hands, r5_score = next_round(
#             current_hands=r5_hands, leads=r5_leads, game_round=5, game_score=r4_score
#         )
#         results = r5_score.reshape(r5_score.shape[0], 5)

#         meta_results = np.zeros(results.shape[0], dtype=np.int64)

#         eval_position = player

#         if eval_position % 2 == 0:
#             for i in range(len(results)):
#                 meta_results[i] = np.sum(results[i]%2)<3
#         else:
#             for i in range(len(results)):
#                 meta_results[i] = np.sum(results[i]%2)>=3

#         resp_win_chances[counter] = np.mean(meta_results)
#         response_hands[counter] = big_mask
#         response_leads[counter] = big_mask

#         counter +=1

#     print(resp_win_chances)

#     return response_hands[np.argmax(resp_win_chances)], response_leads[np.argmax(resp_win_chances)]

In [204]:
# # will likely need multiple perspectives here. 
# r2_best_response(hands=hands5, best_opening_card=best_opener, player=1)