In [1]:
from deck import full_euchre_deck
from dealer import Dealer
from numba import njit
from n_play_round import round1, next_round
from tree_search import find_best_opener, find_best_response, n_trick_sim
import numpy as np


In [2]:
game = Dealer(deck=full_euchre_deck ,players=4)
# game.stack_deck(stack_cards=dealer_pick, player=4)
game.deal_cards()
hands5 = np.array([game.hand1, game.hand2, game.hand3, game.hand4])
hands5

array([[[-13,   0],
        [  0, 110],
        [-14,   0],
        [ -9,   0],
        [ 10,   0]],

       [[-11,   0],
        [-12,   0],
        [ 11,   0],
        [  0,  -9],
        [-10,   0]],

       [[  9,   0],
        [  0, -12],
        [  0, -13],
        [  0, -14],
        [  0,  90]],

       [[  0, 130],
        [  0, 120],
        [  0, -10],
        [  0, 135],
        [  0, 100]]])

In [3]:
best_opener = find_best_opener(hands=hands5, lead=0, tricks=5, previous_winners=np.array([]), sim_func=n_trick_sim)

[0. 0. 0. 0. 0.]


In [4]:
best_opener

np.int64(0)

In [6]:
r2_optimal, winner_round1 = find_best_response(hands=hands5, lead=0, tricks=5, previous_winners=np.array([]), best_opener=best_opener)

Trick Played: 
[[-13   0]
 [-10   0]
 [  9   0]
 [  0 130]]


In [7]:
winner_round1, r2_optimal

(np.int64(3),
 array([[[  0, 110],
         [-14,   0],
         [ -9,   0],
         [ 10,   0]],
 
        [[-11,   0],
         [-12,   0],
         [ 11,   0],
         [  0,  -9]],
 
        [[  0, -12],
         [  0, -13],
         [  0, -14],
         [  0,  90]],
 
        [[  0, 120],
         [  0, -10],
         [  0, 135],
         [  0, 100]]]))

In [8]:
r2_best_opener = find_best_opener(hands=r2_optimal, lead=winner_round1, tricks=4, previous_winners=np.array([winner_round1]), sim_func=n_trick_sim)

[0. 0. 0. 0.]


In [9]:
r3_optimal, winner_round2 = find_best_response(hands=r2_optimal, lead=winner_round1, tricks=4, previous_winners=np.array([winner_round1]), best_opener=r2_best_opener)

Trick Played: 
[[  0 110]
 [  0  -9]
 [  0  90]
 [  0 120]]


In [10]:
r3_optimal, winner_round2

(array([[[-14,   0],
         [ -9,   0],
         [ 10,   0]],
 
        [[-11,   0],
         [-12,   0],
         [ 11,   0]],
 
        [[  0, -12],
         [  0, -13],
         [  0, -14]],
 
        [[  0, -10],
         [  0, 135],
         [  0, 100]]]),
 np.int64(3))

In [11]:
r3_best_opener = find_best_opener(hands=r3_optimal, lead=winner_round2, tricks=3, previous_winners=np.array([winner_round1, winner_round2]), sim_func=n_trick_sim)

[0. 0. 0.]


In [12]:
r4_optimal, winner_round3 = find_best_response(hands=r3_optimal, lead=winner_round2, tricks=3, previous_winners=np.array([winner_round1, winner_round2]), best_opener=r3_best_opener)

Trick Played: 
[[ -9   0]
 [-11   0]
 [  0 -12]
 [  0 -10]]


In [13]:
r4_best_opener = find_best_opener(hands=r4_optimal, lead=winner_round3, tricks=2,previous_winners=np.array([winner_round1, winner_round2, winner_round3]), sim_func=n_trick_sim)

[0. 0.]


In [14]:
r5_optimal, winner_round4 = find_best_response(hands=r4_optimal, lead=winner_round3, tricks=2, previous_winners=np.array([winner_round1, winner_round2, winner_round3]), best_opener=r4_best_opener)

Trick Played: 
[[ 10   0]
 [ 11   0]
 [  0 -13]
 [  0 135]]


In [15]:
r5_best_opener = find_best_opener(hands=r5_optimal, lead=winner_round4, tricks=1, previous_winners=np.array([winner_round1, winner_round2, winner_round3, winner_round4]), sim_func=n_trick_sim)

[0.]


In [16]:
# you should always have a definitive answer by round 5
# 0 = team 'odd' has won 
# 1 = team 'even' has won