In [1]:
from deck import full_euchre_deck
from dealer import Dealer
# from numba import njit
# from n_play_round import round1, next_round
from tree_search import definitive_winner
import numpy as np


In [2]:
game = Dealer(deck=full_euchre_deck ,players=4)
# game.stack_deck(stack_cards=dealer_pick, player=4)
game.deal_cards()
hands5 = np.array([game.hand1, game.hand2, game.hand3, game.hand4])
hands5

array([[[  0, 120],
        [  0, 130],
        [  0,  90],
        [  0, 100],
        [-14,   0]],

       [[-12,   0],
        [  0, 135],
        [-11,   0],
        [ 10,   0],
        [  0, 110]],

       [[  0,  -9],
        [-10,   0],
        [  0, -13],
        [ 12,   0],
        [ 11,   0]],

       [[ -9,   0],
        [ 14,   0],
        [  0, -10],
        [  9,   0],
        [ 13,   0]]])

In [3]:
definitive_winner(given_hands=hands5, verbose=True)

[1.         0.77659574 1.         0.68709677 0.60573477]
Lead 1
Hands: 
[[[  0 120]
  [  0 130]
  [  0  90]
  [  0 100]
  [-14   0]]

 [[-12   0]
  [  0 135]
  [-11   0]
  [ 10   0]
  [  0 110]]

 [[  0  -9]
  [-10   0]
  [  0 -13]
  [ 12   0]
  [ 11   0]]

 [[ -9   0]
  [ 14   0]
  [  0 -10]
  [  9   0]
  [ 13   0]]]
Trick Played: 
[[  0  90]
 [  0 110]
 [  0  -9]
 [  9   0]]
[1.         0.55555556 1.         0.25      ]
Lead 1
Hands: 
[[[  0 120]
  [  0 130]
  [  0 100]
  [-14   0]]

 [[-12   0]
  [  0 135]
  [-11   0]
  [ 10   0]]

 [[-10   0]
  [  0 -13]
  [ 12   0]
  [ 11   0]]

 [[ -9   0]
  [ 14   0]
  [  0 -10]
  [ 13   0]]]
Trick Played: 
[[-14   0]
 [ 10   0]
 [ 12   0]
 [ 14   0]]
[0. 0. 0.]
Lead 3
Hands: 
[[[  0 120]
  [  0 130]
  [  0 100]]

 [[-12   0]
  [  0 135]
  [-11   0]]

 [[-10   0]
  [  0 -13]
  [ 11   0]]

 [[ -9   0]
  [  0 -10]
  [ 13   0]]]
Trick Played: 
[[  0 120]
 [-12   0]
 [-10   0]
 [ -9   0]]
[0. 0.]
Lead 0
Hands: 
[[[  0 130]
  [  0 100]]

 [[  0 135]


0

In [4]:
# it appears that the function for best response relies on the opposing team making mistakes. Need to find a fix for this