In [1]:
from deck import full_euchre_deck
from dealer import Dealer
# from numba import njit
from n_branches import array_set_difference
from n_play_round import round1, next_round
from tree_search import player_best_prune, find_best_opener, n_trick_sim, trick_played
import numpy as np


In [2]:
# game = Dealer(deck=full_euchre_deck ,players=4)
# # game.stack_deck(stack_cards=dealer_pick, player=4)
# game.deal_cards()
# hands_test = np.array([game.hand1, game.hand2, game.hand3, game.hand4])
# hands_test

In [3]:
hands_test = np.array([[[-10,   0],
        [-11,   0],
        [-14,   0],
        [-12,   0],
        [  0, -10]],

       [[  0, -12],
        [  0, -13],
        [  0, -14],
        [-13,   0],
        [  0, 100]],

       [[ 14,   0],
        [  0, 135],
        [ 10,   0],
        [  0,  90],
        [  0,  -9]],

       [[ 12,   0],
        [  0, 140],
        [ 11,   0],
        [  9,   0],
        [  0, 110]]])

In [4]:
# starting_lead = 0
# previous_winners = np.array([])

In [5]:
best_opener = find_best_opener(lead=1, hands=hands_test, tricks=5, previous_winners=np.array([]), sim_func=n_trick_sim, verbose=True)

[0.08497231 0.0704501  0.08239478 0.13834788 0.26409266]


In [6]:
next_best_1, next_best_1_leads = player_best_prune(player=2, first_response=True, starting_hands=hands_test, best_opener=best_opener, starting_lead=1, tricks=5)

In [7]:
next_best_1.shape

(3, 4, 4, 2)

In [8]:
next_best_2, next_best_2_leads = player_best_prune(
    player=3,
    first_response=False,
    best_opener=best_opener,
    starting_lead=1,
    tricks=5,
    given_hands=next_best_1,
    given_leads=next_best_1_leads,
)

In [9]:
next_best_3, next_best_3_leads = player_best_prune(
    player=0,
    first_response=False,
    best_opener=best_opener,
    starting_lead=1,
    tricks=5,
    given_hands=next_best_2,
    given_leads=next_best_2_leads,
)

In [10]:
trick_played(hands_test, next_best_3[0])

array([[  0, -10],
       [  0, -13],
       [  0,  -9],
       [  0, 110]])

In [11]:
r2_hands = next_best_3[0]
r2_leads = next_best_3_leads[0]

In [12]:
r2_leads

np.int64(3)

In [13]:
best_opener_r2 = find_best_opener(
    hands=r2_hands,
    lead=r2_leads,
    tricks=4,
    previous_winners=np.array([r2_leads], dtype=np.int64),
    sim_func=n_trick_sim,
    verbose=True,
)

[0.         0.26666667 0.         0.        ]


In [14]:
next_best_1_r2, next_best_1_r2_leads = player_best_prune(
    player=0,
    first_response=True,
    starting_hands=r2_hands,
    best_opener=best_opener_r2,
    starting_lead=r2_leads,
    tricks=4,
    previous_winners=np.array([r2_leads], dtype=np.int64)
)

In [15]:
next_best_1_r2_leads

array([2, 3, 1, 1])

In [16]:
next_best_2_r2, next_best_2_r2_leads = player_best_prune(
    player=1,
    first_response=False,
    best_opener=best_opener_r2,
    starting_lead=r2_leads,
    tricks=4,
    given_hands=next_best_1_r2,
    given_leads=next_best_1_r2_leads,
    previous_winners=np.array([r2_leads], dtype=np.int64)
)

In [17]:
next_best_2_r2_leads

array([2, 3])

In [18]:
next_best_3_r2, next_best_3_r2_leads = player_best_prune(
    player=2,
    first_response=False,
    best_opener=best_opener_r2,
    starting_lead=r2_leads,
    tricks=4,
    given_hands=next_best_2_r2,
    given_leads=next_best_2_r2_leads,
    previous_winners=np.array([r2_leads], dtype=np.int64)
)

In [ ]:
# I am very confused why there is two still,

# ah, found it, nice
next_best_3_r2, next_best_3_r2_leads


(array([[[[-11,   0],
          [-14,   0],
          [-12,   0]],
 
         [[  0, -14],
          [-13,   0],
          [  0, 100]],
 
         [[  0, 135],
          [ 10,   0],
          [  0,  90]],
 
         [[  0, 140],
          [ 11,   0],
          [  9,   0]]]]),
 array([2]))

In [ ]:
# just need to rinse and repeat this process, then we have a definitive win function (maybe)

trick_played(r2_hands, next_best_3_r2[0])

array([[-10,   0],
       [  0, -12],
       [ 14,   0],
       [ 12,   0]])