In [ ]:
from deck import full_euchre_deck
from dealer import Dealer
# from numba import njit
from tree_search import definitive_winner
import numpy as np


In [ ]:
game = Dealer(deck=full_euchre_deck ,players=4)
game.deal_cards()
hands_test = np.array([game.hand1, game.hand2, game.hand3, game.hand4])
hands_test

array([[[-11,   0],
        [  0, -13],
        [ 13,   0],
        [  9,   0],
        [-10,   0]],

       [[-13,   0],
        [ 12,   0],
        [  0, 140],
        [ 10,   0],
        [  0, 120]],

       [[  0, 135],
        [-14,   0],
        [  0, 100],
        [  0, -10],
        [  0,  90]],

       [[  0, -12],
        [  0,  -9],
        [  0, 130],
        [ 11,   0],
        [  0, 110]]])

In [11]:
definitive_winner(dealt_hands=hands_test, starting_player=1, verbose=True)

[0.29895589 0.37632339 0.57926829 0.35300372 0.51961824]
[0.05154639 0.04672897 0.06015038 0.16041979]
[0.02419355 0.33333333 0.33333333]
[0.5 0. ]
[0.]
Starting hands:
 [[[-11   0]
  [  0 -13]
  [ 13   0]
  [  9   0]
  [-10   0]]

 [[-13   0]
  [ 12   0]
  [  0 140]
  [ 10   0]
  [  0 120]]

 [[  0 135]
  [-14   0]
  [  0 100]
  [  0 -10]
  [  0  90]]

 [[  0 -12]
  [  0  -9]
  [  0 130]
  [ 11   0]
  [  0 110]]]
Trick 1 winner: 3
Trick 1:
 [[-10   0]
 [-13   0]
 [-14   0]
 [  0 110]] None
next round hands:
 [[[-11   0]
  [  0 -13]
  [ 13   0]
  [  9   0]]

 [[ 12   0]
  [  0 140]
  [ 10   0]
  [  0 120]]

 [[  0 135]
  [  0 100]
  [  0 -10]
  [  0  90]]

 [[  0 -12]
  [  0  -9]
  [  0 130]
  [ 11   0]]]
Trick 2: [[  0 -13]
 [ 10   0]
 [  0 -10]
 [  0  -9]]
Trick 2 winner: 0
next round hands:
 [[[-11   0]
  [ 13   0]
  [  9   0]]

 [[ 12   0]
  [  0 140]
  [  0 120]]

 [[  0 135]
  [  0 100]
  [  0  90]]

 [[  0 -12]
  [  0 130]
  [ 11   0]]]
Trick 3:
 [[ 13   0]
 [ 12   0]
 [  0 100]

0