In [7]:
from deck import full_euchre_deck
from dealer import Dealer
# from numba import njit
from tree_search import definitive_winner
from n_game_sim import generate_hands
import numpy as np


In [2]:
evaluate = np.array(
    [  # left bower  (Jack of clubs)
        [0, 140],
        [0, 135],    
        [0, -9],
        [-9, 0], 
        [9, 0]
    ]
)
up_card = np.array(
    [  # left bower  (Jack of clubs)
        [0, 90],  
    ]
)

In [4]:
game = Dealer(deck=full_euchre_deck ,players=4)
game.stack_deck(stack_cards=evaluate, player=0)
game.stack_deck(stack_cards=up_card, player=2)
game.deal_cards()
hands_test = np.array([game.hand0, game.hand1, game.hand2, game.hand3])
hands_test

array([[[  0, 140],
        [  0, 135],
        [  0,  -9],
        [ -9,   0],
        [  9,   0]],

       [[ 13,   0],
        [  0, -14],
        [  0, 100],
        [  0, 110],
        [  0, -10]],

       [[  0,  90],
        [ 10,   0],
        [ 14,   0],
        [-12,   0],
        [ 11,   0]],

       [[-11,   0],
        [-14,   0],
        [ 12,   0],
        [  0, -13],
        [-10,   0]]])

In [ ]:
# quick look at what definitive_winner does
definitive_winner(dealt_hands=hands_test, starting_player=3, caller=0, verbose=True)

[ 0.04489796 -0.48828125  0.75029727  0.52997779  0.04489796]
[-1.44632768 -1.09090909 -0.2        -1.44632768]
[-1.4 -2.  -1.9]
[-2. -2.]
[-2.]
Starting hands:
 [[[  0 140]
  [  0 135]
  [  0  -9]
  [ -9   0]
  [  9   0]]

 [[ 13   0]
  [  0 -14]
  [  0 100]
  [  0 110]
  [  0 -10]]

 [[  0  90]
  [ 10   0]
  [ 14   0]
  [-12   0]
  [ 11   0]]

 [[-11   0]
  [-14   0]
  [ 12   0]
  [  0 -13]
  [-10   0]]]
Trick 1:
 [[ -9   0]
 [  0 -10]
 [-12   0]
 [-14   0]]
Trick 1 winner: 3
next round hands:
 [[[  0 140]
  [  0 135]
  [  0  -9]
  [  9   0]]

 [[ 13   0]
  [  0 -14]
  [  0 100]
  [  0 110]]

 [[  0  90]
  [ 10   0]
  [ 14   0]
  [ 11   0]]

 [[-11   0]
  [ 12   0]
  [  0 -13]
  [-10   0]]]
Trick 2: [[  0 140]
 [ 13   0]
 [ 10   0]
 [-11   0]]
Trick 2 winner: 0
next round hands:
 [[[  0 135]
  [  0  -9]
  [  9   0]]

 [[  0 -14]
  [  0 100]
  [  0 110]]

 [[  0  90]
  [ 14   0]
  [ 11   0]]

 [[ 12   0]
  [  0 -13]
  [-10   0]]]
Trick 3:
 [[  0 135]
 [  0 100]
 [  0  90]
 [-10   0]]


-2

In [ ]:
gen_test = generate_hands(n_games=500, stack=evaluate, stack_player=0, up_card=up_card, up_card_player=1)

In [12]:
scores = np.zeros(500, dtype=np.int64)

for i in range(500):
    scores[i] = definitive_winner(dealt_hands=gen_test[i], starting_player=2, caller=0, verbose=False)

mean_score = np.mean(scores)
se = np.std(scores, ddof=1) / np.sqrt(len(scores))

ci_lower = mean_score - 1.96 * se
ci_upper = mean_score + 1.96 * se

print(f"Expected value: {mean_score:.3f}")
print(f"95% CI: [{ci_lower:.3f}, {ci_upper:.3f}]")

Expected value: -0.012
95% CI: [-0.144, 0.120]
