In [1]:
from deck import full_euchre_deck
from dealer import Dealer
# from numba import njit
from tree_search import definitive_winner
from n_game_sim import generate_hands
import numpy as np


In [2]:
evaluate = np.array(
    [  # left bower  (Jack of clubs)
        [0, 140],
        [0, 135],    
        [0, -9],
        [-9, 0], 
        [9, 0]
    ]
)
up_card = np.array(
    [  # left bower  (Jack of clubs)
        [0, 90],  
    ]
)

In [3]:
# def generate_hands(
#     n_games=100,
#     stack: np.array = None,
#     stack_player: int = None,
#     up_card: np.array = None,
#     up_card_player: int = None,
# ):
#     """Generate n random hand configurations."""
#     all_hands = np.zeros((n_games, 4, 5, 2), dtype=np.int64)

#     for i in range(n_games):
#         game = Dealer(deck=full_euchre_deck, players=4)
#         if stack is not None:
#             game.stack_deck(stack_cards=stack, player=stack_player)
#         if up_card is not None:
#             game.stack_deck(stack_cards=up_card, player=up_card_player)
#         game.deal_cards()
#         all_hands[i] = np.array([game.hand1, game.hand2, game.hand3, game.hand4])

#     return all_hands

In [4]:
game = Dealer(deck=full_euchre_deck ,players=4)
game.stack_deck(stack_cards=evaluate, player=1)
game.stack_deck(stack_cards=up_card, player=2)
game.deal_cards()
hands_test = np.array([game.hand1, game.hand2, game.hand3, game.hand4])
hands_test

array([[[  0, 140],
        [  0, 135],
        [  0,  -9],
        [ -9,   0],
        [  9,   0]],

       [[  0,  90],
        [  0, -12],
        [ 10,   0],
        [  0, 110],
        [ 14,   0]],

       [[  0, -13],
        [-11,   0],
        [ 11,   0],
        [  0, 100],
        [-12,   0]],

       [[ 12,   0],
        [  0, -14],
        [  0, 130],
        [-10,   0],
        [  0, -10]]])

In [5]:
# quick look at what definitive_winner does
definitive_winner(dealt_hands=hands_test, starting_player=3, caller=0, verbose=True)

[-0.05375552 -0.29296527 -0.02089552  0.38357094  1.05509642]
[-1.62025316 -0.35714286 -1.         -0.75417202]
[ 0.  -1.4  0. ]
[-2. -2.]
[-2.]
Starting hands:
 [[[  0 140]
  [  0 135]
  [  0  -9]
  [ -9   0]
  [  9   0]]

 [[  0  90]
  [  0 -12]
  [ 10   0]
  [  0 110]
  [ 14   0]]

 [[  0 -13]
  [-11   0]
  [ 11   0]
  [  0 100]
  [-12   0]]

 [[ 12   0]
  [  0 -14]
  [  0 130]
  [-10   0]
  [  0 -10]]]
Trick 1:
 [[  0  -9]
 [  0 -12]
 [  0 -13]
 [  0 -14]]
Trick 1 winner: 3
next round hands:
 [[[  0 140]
  [  0 135]
  [ -9   0]
  [  9   0]]

 [[  0  90]
  [ 10   0]
  [  0 110]
  [ 14   0]]

 [[-11   0]
  [ 11   0]
  [  0 100]
  [-12   0]]

 [[ 12   0]
  [  0 130]
  [-10   0]
  [  0 -10]]]
Trick 2: [[ 9  0]
 [14  0]
 [11  0]
 [12  0]]
Trick 2 winner: 1
next round hands:
 [[[  0 140]
  [  0 135]
  [ -9   0]]

 [[  0  90]
  [ 10   0]
  [  0 110]]

 [[-11   0]
  [  0 100]
  [-12   0]]

 [[  0 130]
  [-10   0]
  [  0 -10]]]
Trick 3:
 [[  0 140]
 [ 10   0]
 [  0 100]
 [  0 130]]
Trick 3 

-2

In [6]:
gen_test = generate_hands(n_games=500, stack=evaluate, stack_player=1, up_card=up_card, up_card_player=2)

In [7]:
scores = np.zeros(500, dtype=np.int64)

for i in range(500):
    scores[i] = definitive_winner(dealt_hands=gen_test[i], starting_player=3, caller=0, verbose=False)

mean_score = np.mean(scores)
se = np.std(scores, ddof=1) / np.sqrt(len(scores))

ci_lower = mean_score - 1.96 * se
ci_upper = mean_score + 1.96 * se

print(f"Expected value: {mean_score:.3f}")
print(f"95% CI: [{ci_lower:.3f}, {ci_upper:.3f}]")

Expected value: -0.178
95% CI: [-0.315, -0.041]
