In [5]:
# from numba import njit
from tree_search import definitive_winner
import numpy as np
from n_game_sim import generate_hands


In [ ]:
evaluate = np.array(
    [  # left bower  (Jack of clubs)
        [0, 140],
        [0, 135],    
        [0, -9],
        [-9, 0], 
        [9, 0]
    ]
)
up_card = np.array(
    [  # left bower  (Jack of clubs)
        [0, 90],  
    ]
)

In [3]:
# game = Dealer(deck=full_euchre_deck ,players=4)
# game.stack_deck(stack_cards=evaluate, player=0)
# game.stack_deck(stack_cards=up_card, player=2)
# game.deal_cards()
# hands_test = np.array([game.hand0, game.hand1, game.hand2, game.hand3])
# hands_test

In [2]:
hands_test = np.array([[[  0, 140],
        [  0, 135],
        [  0,  -9],
        [ -9,   0],
        [  9,   0]],

       [[ 13,   0],
        [  0, -14],
        [  0, 100],
        [  0, 110],
        [  0, -10]],

       [[  0,  90],
        [ 10,   0],
        [ 14,   0],
        [-12,   0],
        [ 11,   0]],

       [[-11,   0],
        [-14,   0],
        [ 12,   0],
        [  0, -13],
        [-10,   0]]])

In [4]:
# quick look at what definitive_winner does
definitive_winner(dealt_hands=hands_test, starting_player=2, caller=0, verbose=True)

[-0.00816327  0.03731343  1.08376963 -0.28060413  0.03731343]
[1.07407407 1.08695652 1.07741935 1.08695652]
[1. 1. 1.]
[1. 1.]
[1.]
Starting hands:
 [[[  0 140]
  [  0 135]
  [  0  -9]
  [ -9   0]
  [  9   0]]

 [[ 13   0]
  [  0 -14]
  [  0 100]
  [  0 110]
  [  0 -10]]

 [[  0  90]
  [ 10   0]
  [ 14   0]
  [-12   0]
  [ 11   0]]

 [[-11   0]
  [-14   0]
  [ 12   0]
  [  0 -13]
  [-10   0]]]
Trick 1:
 [[ 9  0]
 [13  0]
 [14  0]
 [12  0]]
Trick 1 winner: 2
next round hands:
 [[[  0 140]
  [  0 135]
  [  0  -9]
  [ -9   0]]

 [[  0 -14]
  [  0 100]
  [  0 110]
  [  0 -10]]

 [[  0  90]
  [ 10   0]
  [-12   0]
  [ 11   0]]

 [[-11   0]
  [-14   0]
  [  0 -13]
  [-10   0]]]
Trick 2: [[ -9   0]
 [  0 110]
 [ 10   0]
 [-10   0]]
Trick 2 winner: 1
next round hands:
 [[[  0 140]
  [  0 135]
  [  0  -9]]

 [[  0 -14]
  [  0 100]
  [  0 -10]]

 [[  0  90]
  [-12   0]
  [ 11   0]]

 [[-11   0]
  [-14   0]
  [  0 -13]]]
Trick 3:
 [[  0  -9]
 [  0 -14]
 [  0  90]
 [  0 -13]]
Trick 3 winner: 2
nex

1

In [ ]:
gen_test = generate_hands(n_games=500, stack=evaluate, stack_player=0, up_card=up_card, up_card_player=1)

In [ ]:
scores = np.zeros(500, dtype=np.int64)

for i in range(500):
    scores[i] = definitive_winner(dealt_hands=gen_test[i], starting_player=2, caller=0, verbose=False)

mean_score = np.mean(scores)
se = np.std(scores, ddof=1) / np.sqrt(len(scores))

ci_lower = mean_score - 1.96 * se
ci_upper = mean_score + 1.96 * se

print(f"Expected value: {mean_score:.3f}")
print(f"95% CI: [{ci_lower:.3f}, {ci_upper:.3f}]")

[[0 0 2 3 3]
 [0 2 3 0 2]
 [2 3 0 0 0]
 [3 0 0 0 0]]
[[0 0 0 0 2]
 [0 0 0 2 3]
 [0 0 2 2 2]
 [0 2 2 1 2]
 [2 2 1 1 0]
 [2 1 1 0 0]
 [1 1 0 0 0]
 [1 0 0 0 0]]
[[3 3 0 0 3]
 [3 0 0 0 3]]
[[3 0 0 0 3]]
[[0 0 0 0 1]]
[[1 3 0 0 0]
 [3 0 0 0 0]]
[[2 0 0 0 2]]
[[2 0 0 0 2]]
[[0 0 0 0 1]
 [0 0 0 0 1]]
[[1 1 0 0 0]
 [1 0 0 0 0]]
[[1 1 0 0 1]
 [1 0 0 0 1]]
[[2 0 0 0 1]]
[[1 0 0 0 1]]
[[3 3 0 0 3]
 [3 0 0 0 3]]
[[3 0 0 0 1]]
[[2 3 1 1 1]
 [3 1 1 0 1]
 [1 1 0 0 3]
 [1 0 0 0 3]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[1 3 0 0 2]
 [3 0 0 0 3]]
[[1 2 0 0 3]
 [2 0 0 0 2]]
[[1 0 0 0 1]]
[[1 0 0 0 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[3 0 0 0 3]]
[[3 0 0 0 3]]
[[0 0 0 0 1]
 [0 0 0 0 1]]
[[1 1 1 1 0]
 [1 1 1 0 0]
 [1 1 0 0 0]
 [1 0 0 0 0]]
[[1 0 0 0 1]]
[[1 0 0 0 1]]


SystemError: CPUDispatcher(<function next_round at 0x000001FAE4FBD4E0>) returned a result with an exception set