In [2]:
from deck import full_euchre_deck
from dealer import Dealer
from n_play_round import round1, next_round
import numpy as np
from numba import njit
from n_branches import n_find_winner, array_set_difference, n_ap_filter, nfb_by_hand, n_tricks

In [3]:
loner = np.array([[0, 135], [ 0, 140], [0, 130], [-9, 0], [0, -9]])
loner2 = np.array([[0, 100], [ 0, 90]])

In [4]:
game = Dealer(deck=full_euchre_deck ,players=4)
game.stack_deck(stack_cards=loner, player=1)
game.stack_deck(stack_cards=loner2, player=2)
game.deal_cards()
hands5 = np.array([game.hand1, game.hand2, game.hand3, game.hand4])

In [5]:
hands5

array([[[  0, 135],
        [  0, 140],
        [  0, 130],
        [ -9,   0],
        [  0,  -9]],

       [[  0, 100],
        [  0,  90],
        [  0, -12],
        [ 11,   0],
        [  0, 120]],

       [[ 13,   0],
        [-14,   0],
        [  0, 110],
        [  0, -14],
        [  0, -10]],

       [[ 14,   0],
        [ 10,   0],
        [-11,   0],
        [  0, -13],
        [  9,   0]]])

In [6]:
all_possible_tricks = n_tricks(hands5)
branch = n_ap_filter(tricks=all_possible_tricks, target=hands5[0][0], lead=0)
branch = nfb_by_hand(branch=branch, hand=(0+1)%4, target=hands5[0][0])

In [10]:
branch

array([[[  0, 135],
        [  0, 100],
        [ 13,   0],
        [ 14,   0]],

       [[  0, 135],
        [  0, 100],
        [ 13,   0],
        [ 10,   0]],

       [[  0, 135],
        [  0, 100],
        [ 13,   0],
        [-11,   0]],

       [[  0, 135],
        [  0, 100],
        [ 13,   0],
        [  0, -13]],

       [[  0, 135],
        [  0, 100],
        [ 13,   0],
        [  9,   0]],

       [[  0, 135],
        [  0, 100],
        [-14,   0],
        [ 14,   0]],

       [[  0, 135],
        [  0, 100],
        [-14,   0],
        [ 10,   0]],

       [[  0, 135],
        [  0, 100],
        [-14,   0],
        [-11,   0]],

       [[  0, 135],
        [  0, 100],
        [-14,   0],
        [  0, -13]],

       [[  0, 135],
        [  0, 100],
        [-14,   0],
        [  9,   0]],

       [[  0, 135],
        [  0, 100],
        [  0, 110],
        [ 14,   0]],

       [[  0, 135],
        [  0, 100],
        [  0, 110],
        [ 10,   0]],

       [[  0, 13

In [ ]:
@njit
def common_sense(branch, target, player):
    store_vals = np.zeros(shape=(len(branch), 2), dtype=np.int64)
    for i in range(len(branch)):
        store_vals[i] = branch[i][player] 
    
    store_bools = np.zeros(shape=(len(branch), 2), dtype=np.bool_)
    for j in range(len(store_vals)):
        store_bools[j] =  np.linalg.norm(store_vals[j].astype(np.float64)) < np.linalg.norm(target.astype(np.float64)) 

    # in the case this is true, just grab the argmin for stored_vals after finding the card worth. I guess
    return np.all(store_bools)

In [23]:
common_sense(branch=branch, target=hands5[0][0], player=1)

True

In [9]:
stop

NameError: name 'stop' is not defined

In [ ]:
r2_leads, r2_hands = round1(hands_dealt=hands5)

In [ ]:
r3_leads, r3_hands, r2_score = next_round(current_hands=r2_hands, leads=r2_leads, game_round=2, game_score=r2_leads.reshape(-1, 1))

4424


In [ ]:
r4_leads, r4_hands, r3_score = next_round(current_hands=r3_hands, leads=r3_leads, game_round=3, game_score=r2_score)

125595


In [ ]:
r5_leads, r5_hands, r4_score = next_round(current_hands=r4_hands, leads=r4_leads, game_round=4, game_score=r3_score)

1116432


In [ ]:
r6_leads, r6_hands, r5_score = next_round(current_hands=r5_hands, leads=r5_leads, game_round=5, game_score=r4_score)

1116432


In [ ]:
results = r5_score.reshape(r5_score.shape[0], 5)

In [ ]:
results

array([[0, 0, 2, 2, 2],
       [0, 0, 2, 2, 2],
       [0, 0, 2, 2, 2],
       ...,
       [3, 1, 3, 0, 0],
       [3, 1, 3, 0, 0],
       [3, 1, 3, 0, 0]])

In [ ]:
np.mean([sum(i)<3 for i in results%2])

np.float64(0.8119007695945656)