In [109]:
import numpy as np
from deck import full_euchre_deck, card_evaluator
from dealer import dealer

In [110]:
game = dealer(deck=full_euchre_deck ,players=4)
game.deal_cards()
hands = [game.hand1, game.hand2, game.hand3, game.hand4]


In [111]:
game.hand1

array([[  0,  12],
       [  0, -11],
       [ 10,   0],
       [ -9,   0],
       [  0,  -9]])

In [112]:
# all playable hands
grids = np.meshgrid(*[np.arange(len(a)) for a in hands], indexing='ij')
product_indices = np.stack(grids, axis=-1).reshape(-1, len(hands))

# Gather the cross product result based on indices, 625 results total
cross_product = np.array([[hands[i][idx] for i, idx in enumerate(row)] for row in product_indices])

In [113]:
target = np.array(game.hand1[0])

# Find indices where the subarray equals [0, 10]
contains_target = np.any(np.all(cross_product == target, axis=-1), axis=1)

# Use the boolean mask to return only rows containing [0, 10]
branch1 = cross_product[contains_target]

In [ ]:
follows_suit = [coord for coord in hand if (coord[0] == 0 and coord[1] > 0) or coord[1] == -14]

In [115]:
game.hand2, game.hand3, game.hand4

(array([[11,  0],
        [ 0, 14],
        [14,  0],
        [ 9,  0],
        [12,  0]]),
 array([[  0,  10],
        [-14,   0],
        [-13,   0],
        [-12,   0],
        [-11,   0]]),
 array([[  0, -12],
        [  0,  11],
        [  0, -10],
        [  0,   9],
        [ 13,   0]]))

In [116]:
def filter_branch_by_hand(branch, hand, column_idx):
    follows_suit = [coord for coord in hand if (coord[0] == 0 and coord[1] > 0) or coord[1] == -14]
    follows_suit_arr = np.array(follows_suit)
    
    if len(follows_suit_arr) > 0:
        matches = np.any([np.all(branch[:, column_idx] == i, axis=1) for i in follows_suit_arr], axis=0)
        branch = branch[matches]
    
    return branch

# Now use it for each hand
branch1 = filter_branch_by_hand(branch1, game.hand2, 1)
branch1 = filter_branch_by_hand(branch1, game.hand3, 2)
branch1 = filter_branch_by_hand(branch1, game.hand4, 3)

branch1

array([[[ 0, 12],
        [ 0, 14],
        [ 0, 10],
        [ 0, 11]],

       [[ 0, 12],
        [ 0, 14],
        [ 0, 10],
        [ 0,  9]]])